In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import unicodedata
import urllib3
urllib3.disable_warnings()

In [82]:
num=list(range(250,286,1))

cap=[]
chain=[]
coins=[]
vote=[]
date=[]

for n in num:
    page = requests.get("https://coinvote.cc/alltime&page="+str(n), verify=False)
    html = BeautifulSoup(page.content, 'html.parser')
    foo=list(html.children)[3]
    s=[]
    for i in range(len(list(foo.find_all(class_="coin-column-title redirect-coin")))):
        s.append(list(foo.find_all(class_="coin-column-title redirect-coin"))[i].get_text().replace("\n"," "))

    for i in range (1,len(s),3):
        cap.append(s[i])

    for i in range (0,len(s),3):
        chain.append(s[i])

    for i in range(len(list(foo.find_all(class_="titre-coin")))):
        coins.append(list(foo.find_all(class_="titre-coin"))[i].get_text().replace("\n"," ").split("(")[0])

    for i in range(len(list(foo.find_all(class_="btn btn-primary btn-vote")))):
        vote.append(list(foo.find_all(class_="btn btn-primary btn-vote"))[i].get_text()[2:])

    for i in range (2,len(s),3):
        date.append(s[i].replace("\r","")) 

df=pd.DataFrame()
df["Coins"]=coins
df["Chain"]=chain
df["Launched Since"]=date
df["Cap"]=cap
df["Votes"]=vote
df

ValueError: Length of values (1116) does not match length of index (1152)

In [73]:
vu = df["Coins"].tolist()
tickers=[]
for c in vu:
    tickers.append(c.replace(" ","-"))

In [75]:
telegram=[]
tickerss=[]
link=[]
zaza=[]
tg="https://t.me/"
for t in tickers:
    tickerss.append(unicodedata.normalize("NFKD", t))
for t in tickerss:
    tick=requests.get("https://coinvote.cc/coin/"+str(t), verify=False)
    html5=BeautifulSoup(tick.content, 'html.parser')
    body = list(html5.children)[3]    
    if tick.status_code!=200:
        telegram.append("Null")
    else:
        for i in body.find_all(class_="btn btn-primary btn-vote", href=True):
            if tg in i["href"]:
                telegram.append(i["href"])
            else:
                pass

In [76]:
for t in tickerss:
    tick=requests.get("https://coinvote.cc/coin/"+str(t))
    html5=BeautifulSoup(tick.content, 'html.parser')
    body = list(html5.children)[3]
    if tick.status_code!=200:
        zaza.append("null")
    elif len(body.find_all(class_='coin-bsc'))!=0:
        f=body.find_all(class_="coin-bsc")[0].get_text().replace("\xa0\r\t\t\t\t","")
        zaza.append(f.replace("\n","").replace("\t","")[:-5])
    elif len(body.find_all(class_='coin-bsc'))==0:
        zaza.append("null")
for z in zaza:
    link.append(z.replace("\xa0\r\t\t\t\t","").replace("\xa0","").replace("\r","").replace(" ","").replace("\t",""))

In [77]:
df["Telegram"]=pd.Series(telegram)
df["Adress"]=pd.Series(link)
df

,Coins,Chain,Launched Since,Cap,Votes,Telegram,Adress
0,SafeReal,BSC,4 months ...,"$ 10,923",3949,https://t.me/safereal,0xa3e8f9781bc5ec14b589a7ae85996dfb96c25717
1,Bitcoin Banana,BSC,3 months ...,"$ 5,076,124",3949,https://t.me/BIBAOfficialchat,0x8d5cdc96835acab9e626d44f7efa9c9010146710
2,HoneyFarm,BSC,2 months ...,$ 0.00,3946,https://t.me/HONEYFARMCHAT,0xFa363022816aBf82f18a9C2809dCd2BB393F6AC5
3,Health Token,BSC,5 months ...,"$ 63,007",3946,https://t.me/officialhealthtoken,0x2bd7e7aed93d79d7d8a6d23dc7defc7d6b5d84ad
4,Retro Token,BSC,5 months ...,"$ 16,546",3935,https://t.me/RetroBSC,0x8b3c0Ace6fbAbD607BC2A12b1Fb829FC17F2a4Ce
...,...,...,...,...,...,...,...
5885,Big Doge,BSC,630 months ...,-,0,NaN,0xb51A5a60214E3D8C62e6d43c214bF08139aa0884
5886,CaptainADA,BSC,3 months ...,$ 467,0,NaN,0x11602b0369d3b466ab6ff5fa81beb4311cbe70a6
5887,MOONDOG,BSC,5 months ...,"$ 58,404",0,NaN,0x619eb7d30df94dc4e729f4a0891f745ebf3f896c
5888,Dogeart,BSC,2 months ...,"$ 3,499",0,NaN,0x423a7d17018b8d59389bcb3c4dce6f7322a99496
5889,DryCakeSwap,BSC,8 months ...,-,0,NaN,0x4f51bccd40e0f2f4ab881b7c2be586655f9b3a63

In [13]:
def scrap_regular_1():
    page = requests.get("https://coinvote.cc/alltime&page=1", verify=False)
    html = BeautifulSoup(page.content, 'html.parser')
    foo=list(html.children)[3]
    s=[]
    for i in range(len(list(foo.find(class_ = "regular-table").find_all(class_="coin-column-title redirect-coin")))):
        s.append(list(foo.find(class_ = "regular-table").find_all(class_="coin-column-title redirect-coin"))[i].get_text().replace("\n"," "))
    cap=[]
    for i in range (1,len(s),3):
        cap.append(s[i])
    chain=[]
    for i in range (0,len(s),3):
        chain.append(s[i])
    coins=[]
    for i in range(len(list(foo.find(class_ = "regular-table").find_all(class_="titre-coin")))):
        coins.append(list(foo.find(class_ = "regular-table").find_all(class_="titre-coin"))[i].get_text().replace("\n"," ").split("(")[0])
    vote=[]
    for i in range(len(list(foo.find(class_ = "regular-table").find_all(class_="btn btn-primary btn-vote")))):
        vote.append(list(foo.find(class_ = "regular-table").find_all(class_="btn btn-primary btn-vote"))[i].get_text()[2:])
    date=[]
    for i in range (2,len(s),3):
        date.append(s[i].replace("\r",""))
    df=pd.DataFrame()
    df["Coins"]=coins
    df["Chain"]=chain
    df["Launched Since"]=date
    df["Cap"]=cap
    df["Votes"]=vote
    vu = df["Coins"].tolist()
    tickers=[]
    for c in vu:
        tickers.append(c.replace(" ","-"))
    telegram=[]
    tickerss=[]
    link=[]
    zaza=[]
    for t in tickers:
        tickerss.append(unicodedata.normalize("NFKD", t))
    for t in tickerss:
        tick=requests.get("https://coinvote.cc/coin/"+str(t))
        html5=BeautifulSoup(tick.content, 'html.parser')
        body = list(html5.children)[3]
        telegram.append(body.find_all(class_="btn btn-primary btn-vote", href=True)[2]['href'])
    for t in tickerss:
        tick=requests.get("https://coinvote.cc/coin/"+str(t))
        html5=BeautifulSoup(tick.content, 'html.parser')
        body = list(html5.children)[3]
        if body.find(class_='coin-bsc')==None:
            zaza.append("null")
        else:
            f=body.find_all(class_="coin-bsc")[0].get_text().replace("\xa0\r\t\t\t\t","")
            zaza.append(f.replace("\n","").replace("\t","")[:-5])
    for z in zaza:
        link.append(z.replace("\xa0\r\t\t\t\t","").replace("\xa0","").replace("\r","").replace(" ","").replace("\t",""))
    df["Telegram"]=telegram
    df["Adress"]=link
    
    return df
df1=scrap_regular_1()

In [18]:
ext=pd.concat([df1,df])
ext.to_excel("Max60pages.xlsx")

In [23]:
df0=df1

In [28]:
df1=df
df1

,Coins,Chain,Launched Since,Cap,Votes,Telegram,Adress
0,Coin Launch Pad,BSC,2 months ...,-,89014,https://t.me/COINLAUNCHPAD_OFFICIAL,0xa08c817DD0D5cfc6A13134d2C9f9c9ee42cbfA1c
1,BurnDoge,BSC,2 months ...,-,88072,https://t.me/BURNDOGECOMMUNITY,null
2,Cardence,BSC,2 months ...,-,86728,https://t.me/CARDENCE_CHAT,Presale
3,WenLambo,BSC,5 months ...,"$ 791,363",84864,https://t.me/WenLambo1,0xd8a31016cd7da048ca21ffe04256c6d08c3a2251
4,Baby Koala,BSC,2 months ...,-,84513,https://t.me/babykoalatoken,null
...,...,...,...,...,...,...,...
1793,ICON ELONMUSK,BSC,3 months ...,"$ 49,806",3962,NaN,0x291a52c9bd992d0d02ce5e890ef4d7103082724a
1794,ALL STAR DOGE,BSC,4 months ...,"$ 7,877,760",3961,NaN,0x5584b9b7e6425FC690Bb07A2d708653283755b25
1795,InfiniteOne,BSC,1 month ...,"$ 5,113,074",3960,NaN,0xfcac1a3ede7b55cc51e3ebff2885a67fbfe01a1a
1796,Godl,ETH,3 months ...,-,3958,NaN,0x7f509465C38B66BDeCEC2CfDc842e11809CC8357
1797,NFTmall,BSC,4 months ...,"$ 4,192,254",3957,NaN,0xBaC1df744df160877cDc45E13d0394c06bC388Ff

In [31]:
df2=df

,Coins,Chain,Launched Since,Cap,Votes
0,SafeReal,BSC,4 months ...,"$ 10,923",3949
1,Bitcoin Banana,BSC,3 months ...,"$ 5,076,124",3949
2,HoneyFarm,BSC,2 months ...,$ 0.00,3946
3,Health Token,BSC,5 months ...,"$ 63,007",3946
4,Retro Token,BSC,5 months ...,"$ 16,546",3935
...,...,...,...,...,...
305,Clewee,ETH,4 months ...,-,2993
306,FLY ME,BSC,1 month ...,-,2992
307,stickybuns,BSC,2 days,$ 0,2988
308,PocketRocket,BSC,5 months ...,$ 820,2982
309,SafeTesla,BSC,6 months ...,"$ 326,869",2977

In [81]:
v=pd.read_excel("Max60pages.xlsx")
v=v.drop(labels=["Unnamed: 0"], axis=1)
po=pd.concat([v,df])
# po.to_excel("250pages.xlsx")
po

,Coins,Chain,Launched Since,Cap,Votes,Telegram,Adress
0,HRB,BSC,2 months ...,-,215641,https://discord.com/invite/PcetkQctMF,0x8D58a9254a84275C5449589527a5DDF85FFF6d6D
1,Space Token,BSC,5 months ...,"$ 45,280,591",212450,https://t.me/SpaceTokenBSC,0x9d9affac2175ef541642035ab66f5fe7df813851
2,NFT MARS,BSC,3 months ...,"$ 17,152",209730,https://t.me/Nftmars_Community,0xB10b0A3B5A970875c36C248Fcd3F1acb3622CF3E
3,TrusterCoin,BSC,1 month ...,"$ 30,890,587",188720,https://www.instagram.com/trustercoin/,0xA2a26349448ddAfAe34949a6Cc2cEcF78c0497aC
4,CarbonDEFI Finance,BSC,6 months ...,-,158236,https://t.me/carbondefigroup,0xb05139B021aAEa472b94528B030844D84a6724d5
...,...,...,...,...,...,...,...
5885,Big Doge,BSC,630 months ...,-,0,NaN,0xb51A5a60214E3D8C62e6d43c214bF08139aa0884
5886,CaptainADA,BSC,3 months ...,$ 467,0,NaN,0x11602b0369d3b466ab6ff5fa81beb4311cbe70a6
5887,MOONDOG,BSC,5 months ...,"$ 58,404",0,NaN,0x619eb7d30df94dc4e729f4a0891f745ebf3f896c
5888,Dogeart,BSC,2 months ...,"$ 3,499",0,NaN,0x423a7d17018b8d59389bcb3c4dce6f7322a99496
5889,DryCakeSwap,BSC,8 months ...,-,0,NaN,0x4f51bccd40e0f2f4ab881b7c2be586655f9b3a63